name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-facebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test Facebook
        run: |
          cd facebook
          go test -v --race

  test-tokenstorage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test TokenStorage
        run: |
          cd tokenstorage
          go test -v --race

  test-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Test Utils
        run: |
          cd utils
          go test -v --race
          
  test-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Test Email
        run: |
          cd email
          go test -v --race
          
  test-yandexgames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Test Yandex Games
        run: |
          cd yandexgames
          go test -v --race
          
  lint-facebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Facebook
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40
          working-directory: facebook
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

  lint-tokenstorage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint TokenStorage
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40
          working-directory: tokenstorage
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

  lint-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Utils
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40
          working-directory: utils
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          
  lint-google:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Google
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40
          working-directory: google
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

  lint-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Email
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40
          working-directory: email
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

  lint-yandexgames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Yandex Games
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40
          working-directory: yandexgames
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
